[workspace]
resolver = "2"
members = [ "macro" ]

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = [ "Frand <frand.nano@gmail.com>" ]
repository = "https://github.com/frand-nano/frand-node"

[package]
name = "frand-node"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
frand-node-macro = { path = "macro" }
log = "0.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
crossbeam = "0.8"
ciborium = "0.2"

[dev-dependencies]
simplelog = "0.12"