[workspace]
resolver = "2"
members = [ "macro" ]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = [ "Frand <frand.nano@gmail.com>" ]
repository = "https://github.com/frand-nano/frand-node"

[package]
name = "frand-node"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
frand-node-macro = { path = "macro" }